//
//  Pragmatic_Clean_ArchitectureTests-Pragmatic_Clean_ArchitectureMocks.generated.swift
//  Pragmatic_Clean_Architecture
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import Pragmatic_Clean_Architecture
import Alamofire
import Foundation
import Resolver
import RxSwift
import Swift
import SwiftUI

private let mkbGenericStaticMockContext = Mockingbird.GenericStaticMockContext()

// MARK: - Mocked ArticlesService
public final class ArticlesServiceMock: Pragmatic_Clean_Architecture.ArticlesService, Mockingbird.Mock {
  typealias MockingbirdSupertype = Pragmatic_Clean_Architecture.ArticlesService
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "Pragmatic_Clean_Architecture"])

  fileprivate init(sourceLocation: Mockingbird.SourceLocation) {
    self.mockingbirdContext.sourceLocation = sourceLocation
    ArticlesServiceMock.mockingbirdContext.sourceLocation = sourceLocation
  }

  // MARK: Mocked `fetchArticles`()
  public func `fetchArticles`() -> Observable<[Pragmatic_Clean_Architecture.ArticleRaw]> {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`fetchArticles`() -> Observable<[Pragmatic_Clean_Architecture.ArticleRaw]>", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Observable<[Pragmatic_Clean_Architecture.ArticleRaw]>).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Observable<[Pragmatic_Clean_Architecture.ArticleRaw]> { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Observable<[Pragmatic_Clean_Architecture.ArticleRaw]> = mkbObject.`fetchArticles`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Observable<[Pragmatic_Clean_Architecture.ArticleRaw]>).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `fetchArticles`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Observable<[Pragmatic_Clean_Architecture.ArticleRaw]>, Observable<[Pragmatic_Clean_Architecture.ArticleRaw]>> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Observable<[Pragmatic_Clean_Architecture.ArticleRaw]>, Observable<[Pragmatic_Clean_Architecture.ArticleRaw]>>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`fetchArticles`() -> Observable<[Pragmatic_Clean_Architecture.ArticleRaw]>", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Observable<[Pragmatic_Clean_Architecture.ArticleRaw]>).self)))
  }

  // MARK: Mocked `likeArticle`(`id`: String)
  public func `likeArticle`(`id`: String) -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`likeArticle`(`id`: String) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`id`)], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (String) -> Void { return mkbImpl(`id`) }
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`likeArticle`(id: `id`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `likeArticle`(`id`: @autoclosure () -> String) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`likeArticle`(`id`: String) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`id`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }
}

/// Returns a concrete mock of `ArticlesService`.
public func mock(_ type: Pragmatic_Clean_Architecture.ArticlesService.Protocol, file: StaticString = #file, line: UInt = #line) -> ArticlesServiceMock {
  return ArticlesServiceMock(sourceLocation: Mockingbird.SourceLocation(file, line))
}
